# Copyright (C) 2024-2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
helm_charts_base: "{{ lookup('env', 'PWD') }}/helm-charts"
remote_home_dir: "{{ lookup('env', 'PWD') }}/scripts"
remote_helm_charts_base: "/tmp/helm-charts"
ansible_python_interpreter: /usr/bin/python3
remote_home_scripts_dir: "{{ lookup('env', 'PWD') }}/scripts"
docker_registry_server: "{{ lookup('env', 'docker_registry_server') | default('', true) }}"
docker_registry_username: "{{ lookup('env', 'docker_registry_username') | default('', true) }}"
docker_registry_password: "{{ lookup('env', 'docker_registry_password') | default('', true) }}"
docker_registry_email: "{{ lookup('env', 'docker_registry_email') | default('', true) }}"
docker_registry_secret_name: "{{ lookup('env', 'docker_registry_secret_name') | default('regcred', true) }}"
docker_registry_enabled: "{{ (docker_registry_server | length > 0) and (docker_registry_username | length > 0) and (docker_registry_password | length > 0) }}"